class HandStrength {

    var boardCardsStringList : MutableList<String> = mutableListOf()

    init {
        putCombosInboardCards("AA")
        putCombosInboardCards("KK")
        putCombosInboardCards("QQ")
        putCombosInboardCards("AKs")
        putCombosInboardCards("JJ")
        putCombosInboardCards("AKo")
        putCombosInboardCards("AQs")
        putCombosInboardCards("TT")
        putCombosInboardCards("AJs")
        putCombosInboardCards("AQo")
        putCombosInboardCards("KQs")
        putCombosInboardCards("ATs")
        putCombosInboardCards("KJs")
        putCombosInboardCards("99")
        putCombosInboardCards("KTs")
        putCombosInboardCards("QJs")
        putCombosInboardCards("88")
        putCombosInboardCards("QTs")
        putCombosInboardCards("JTs")
        putCombosInboardCards("A9s")
        putCombosInboardCards("AJo")
        putCombosInboardCards("KQo")
        putCombosInboardCards("77")
        putCombosInboardCards("K9s")
        putCombosInboardCards("ATo")
        putCombosInboardCards("A8s")
        putCombosInboardCards("T9s")
        putCombosInboardCards("66")
        putCombosInboardCards("A7s")
        putCombosInboardCards("55")
        putCombosInboardCards("A5s")
        putCombosInboardCards("A6s")
        putCombosInboardCards("A4s")
        putCombosInboardCards("J9s")
        putCombosInboardCards("KJo")
        putCombosInboardCards("Q9s")
        putCombosInboardCards("44")
        putCombosInboardCards("A3s")
        putCombosInboardCards("KTo")
        putCombosInboardCards("K8s")
        putCombosInboardCards("A2s")
        putCombosInboardCards("T8s")
        putCombosInboardCards("98s")
        putCombosInboardCards("QJo")
        putCombosInboardCards("A9o")
        putCombosInboardCards("QTo")
        putCombosInboardCards("33")
        putCombosInboardCards("K7s")
        putCombosInboardCards("K6s")
        putCombosInboardCards("Q8s")
        putCombosInboardCards("K5s")
        putCombosInboardCards("87s")
        putCombosInboardCards("97s")
        putCombosInboardCards("J8s")
        putCombosInboardCards("87s")
        putCombosInboardCards("76s")
        putCombosInboardCards("65s")
        putCombosInboardCards("JTo")
        putCombosInboardCards("T7s")
        putCombosInboardCards("86s")
        putCombosInboardCards("A8o")
        putCombosInboardCards("K4s")
        putCombosInboardCards("96s")
        putCombosInboardCards("Q7s")
        putCombosInboardCards("Q6s")
        putCombosInboardCards("T9o")
        putCombosInboardCards("J7s")
        putCombosInboardCards("K3s")
        putCombosInboardCards("75s")
        putCombosInboardCards("K9o")
        putCombosInboardCards("T6s")
        putCombosInboardCards("Q5s")
        putCombosInboardCards("Q9o")
        putCombosInboardCards("J9o")
        putCombosInboardCards("A7o")
        putCombosInboardCards("K2s")
        putCombosInboardCards("64s")
        putCombosInboardCards("A5o")
        putCombosInboardCards("J6s")
        putCombosInboardCards("85s")
        putCombosInboardCards("22")
        putCombosInboardCards("T5s")
        putCombosInboardCards("J5s")
        putCombosInboardCards("Q4s")
        putCombosInboardCards("T8o")
        putCombosInboardCards("98o")
        putCombosInboardCards("A4o")
        putCombosInboardCards("95s")
        putCombosInboardCards("Q3s")
        putCombosInboardCards("54s")
        putCombosInboardCards("T5s")
        putCombosInboardCards("J5s")
        putCombosInboardCards("Q4s")
        putCombosInboardCards("T8o")
        putCombosInboardCards("98o")
        putCombosInboardCards("A4o")
        putCombosInboardCards("95s")
        putCombosInboardCards("Q3s")
        putCombosInboardCards("43s")
        putCombosInboardCards("53s")
    }

    private fun putCombosInboardCards(handString : String) {
        val comboOfHands = when {
            handString.length == 2 -> 4
            handString.contains("o") -> 12
            handString.contains("s") -> 6
            else -> -1
        }

        for(i in 0 until comboOfHands) {
            boardCardsStringList.add(handString)
        }

    }

    override fun toString(): String {
        return boardCardsStringList.toString()
    }
}
